export const GET_MODELS_REQUEST = "GET_MODELS_REQUEST";
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_FAILURE = "GET_MODELS_FAILURE";
export const ADD_MODEL_REQUEST = "ADD_MODEL_REQUEST";
export const ADD_MODEL_SUCCESS = "ADD_MODEL_SUCCESS";
export const ADD_MODEL_FAILURE = "ADD_MODEL_FAILURE";